source "http://rubygems.org"
gem "aruba", :git => "https://github.com/iconoclast/aruba.git", :branch => "jruby_fixes"
gem "cucumber"
gem "json_spec"
gem "capybara"
gem "yajl-ruby"
gem "rest-client"
gem "jruby-openssl"
